# Generated by Django 4.2.7 on 2023-12-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=8)),
                ("nombre", models.CharField(max_length=30)),
                ("precio_compra", models.FloatField()),
                ("precio_venta", models.FloatField()),
                ("fecha_compra", models.DateField()),
                ("fecha_registro", models.DateField(auto_now_add=True)),
                ("estado", models.CharField(max_length=1)),
            ],
        ),
    ]
