# Generated by Django 4.2.6 on 2023-12-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=8)),
                ("nombre", models.CharField(max_length=40)),
                ("horas", models.CharField(max_length=8)),
                ("creditos", models.CharField(max_length=3)),
                ("fecha_registro", models.DateField(auto_now_add=True)),
                ("estado", models.CharField(max_length=1)),
            ],
        ),
    ]
